services:
  - type: web
    name: online-testing-app
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: testing-db
          property: connectionString
databases:
  - name: testing-db
    databaseName: testingdb
    user: testinguser
    plan: free
